<?php

namespace Augwa\PaymentGateway\Enum;

/**
 * Class ChasePaymentech
 * @package Augwa\PaymentGateway\Enum
 */
class ChasePaymentech
{

    const INDUSTRY_TYPE_MAIL_ORDER = 'MO';
    const INDUSTRY_TYPE_RECURRING_PAYMENT = 'RC';
    const INDUSTRY_TYPE_ECOMMERCE = 'EC';
    const INDUSTRY_TYPE_IVR = 'IV';
    const INDUSTRY_TYPE_INSTALLMENT = 'IN';

    const MESSAGE_TYPE_AUTHORIZATION_REQUEST = 'A';
    const MESSAGE_TYPE_AUTHORIZATION_CAPTURE_REQUEST = 'AC';
    const MESSAGE_TYPE_FORCE_CAPTURE_REQUEST = 'FC';
    const MESSAGE_TYPE_REFUND_REQUEST = 'R';

    const CARD_BRAND_BILL_ME_LATER = 'BL';
    const CARD_BRAND_PINLESS_DEBIT = 'DP';
    const CARD_BRAND_ELECTRONIC_CHECK = 'EC';
    const CARD_BRAND_EUROPEAN_DIRECT_DEBIT = 'ED';
    const CARD_BRAND_INTERNATIONAL_MAESTRO = 'IM';
    const CARD_BRAND_CHASENET_CREDIT_CARD = 'CZ';
    const CARD_BRAND_CHASENET_SIGNATURE_DEBIT = 'CR';

    const BIN_SALEM = '000001';
    const BIN_PNS = '000002';

    const CARD_CCV_PRESENT = 1;
    const CARD_CCV_ILLEGIBLE = 2;
    const CARD_CCV_NOT_PRESENT = 9;

    const CDPT_INITIAL_AUTHORIZATION = 'Y';
    const CDPT_SUBSEQUENT_AUTHORIZATION = 'S';

    const CUSTOMER_PROFILE_ACTION_CREATE = 'C';
    const CUSTOMER_PROFILE_ACTION_READ = 'R';
    const CUSTOMER_PROFILE_ACTION_UPDATE = 'U';
    const CUSTOMER_PROFILE_ACTION_DELETE = 'D';

    const CUSTOMER_PROFILE_GENERATION_AUTO = 'A';
    const CUSTOMER_PROFILE_GENERATION_REFERENCE_NUM = 'S';
    const CUSTOMER_PROFILE_GENERATION_ORDER_ID = 'O';
    const CUSTOMER_PROFILE_GENERATION_COMMENTS = 'D';

    const CUSTOMER_PROFILE_ORDER_OVERRIDE_MAPPING_NONE = 'NO';
    const CUSTOMER_PROFILE_ORDER_OVERRIDE_MAPPING_ORDER_ID = 'OI';
    const CUSTOMER_PROFILE_ORDER_OVERRIDE_MAPPING_COMMENTS = 'OD';
    const CUSTOMER_PROFILE_ORDER_OVERRIDE_MAPPING_ORDER_ID_COMMENTS = 'OA';

    const CUSTOMER_ACCOUNT_TYPE_CREDIT_CARD = 'CC';
    const CUSTOMER_ACCOUNT_TYPE_PINLESS_DEBIT = 'DP';
    const CUSTOMER_ACCOUNT_TYPE_ELECTRONIC_CHECK = 'EC';
    const CUSTOMER_ACCOUNT_TYPE_EUROPEAN_DIRECT_DEBIT = 'ED';
    const CUSTOMER_ACCOUNT_TYPE_INTERNATIONAL_MAESTRO = 'IM';
    const CUSTOMER_ACCOUNT_TYPE_CHASENET_CREDIT_CARD = 'CZ';
    const CUSTOMER_ACCOUNT_TYPE_CHASENET_SIGNATURE_DEBIT = 'CR';
    const CUSTOMER_ACCOUNT_TYPE_CHASENET_AUTO_ASSIGN = 'AA';

    const CUSTOMER_PROFILE_STATUS_ACTIVE = 'A';
    const CUSTOMER_PROFILE_STATUS_INACTIVE = 'I';
    const CUSTOMER_PROFILE_STATUS_MANUAL_SUSPEND = 'MS';

    const CURRENCY_ALGERIAN_DINAR = '012';
    const CURRENCY_ARGENTINE_PESO = '032';
    const CURRENCY_ARMENIAN_DRAM = '051';
    const CURRENCY_ARUBAN_GUILDER = '533';
    const CURRENCY_AUSTRALIAN_DOLLAR = '036';
    const CURRENCY_AZERBAIJANIAN_MANAT = '031';
    const CURRENCY_BAHAMIAN_DOLLAR = '044';
    const CURRENCY_BANGLADESHI_TAKA = '050';
    const CURRENCY_BARBADOS_DOLLAR = '052';
    const CURRENCY_BELARUSSIAN_RUBLE = '974';
    const CURRENCY_BELIZE_DOLLAR = '084';
    const CURRENCY_BERMUDIAN_DOLLAR = '060';
    const CURRENCY_BOLIVIAN_BOLIVIANO = '068';
    const CURRENCY_BOTSWANA_PULA = '072';
    const CURRENCY_BRAZILIAN_REAL = '986';
    const CURRENCY_BRITISH_POUND = '826';
    const CURRENCY_BRUNEI_DOLLAR = '096';
    const CURRENCY_BULGARIAN_LEV = '975';
    const CURRENCY_BURUNDI_FRANC = '108';
    const CURRENCY_CAMBODIAN_RIEL = '116';
    const CURRENCY_CANADIAN_DOLLAR = '124';
    const CURRENCY_CAPE_VERDI_ESCUDO = '132';
    const CURRENCY_CAYMAN_ISLANDS_DOLLAR = '136';
    const CURRENCY_CFA_FRANC_BCEAO = '952';
    const CURRENCY_CFA_FRANC_BEAC = '950';
    const CURRENCY_CFP_FRANC = '953';
    const CURRENCY_CHILEAN_PESO = '152';
    const CURRENCY_CHINESE_YUAN_RENMINBI = '156';
    const CURRENCY_COLOMBIAN_PESO = '170';
    const CURRENCY_COMORO_FRANC = '174';
    const CURRENCY_COSTA_RICAN_COLON = '188';
    const CURRENCY_CZECH_KORUNA = '203';
    const CURRENCY_DANISH_KRONE = '208';
    const CURRENCY_DJIBOUTI_FRANC = '262';
    const CURRENCY_DOMINICAN_PESO = '214';
    const CURRENCY_EAST_CARIBBEAN_DOLLAR = '951';
    const CURRENCY_EGYPTIAN_POUND = '818';
    const CURRENCY_EL_SALVADOR_COLON = '222';
    const CURRENCY_ESTONIAN_KROON = '233';
    const CURRENCY_ETHIOPIAN_BIRR = '230';
    const CURRENCY_EURO = '978';
    const CURRENCY_FALKLAND_ISLANDS_POUND = '238';
    const CURRENCY_FIJI_DOLLAR = '242';
    const CURRENCY_GAMBIAN_DALASI = '270';
    const CURRENCY_GEORGIAN_LARI = '981';
    const CURRENCY_GHANAIAN_CEDI = '288';
    const CURRENCY_GIBRALTAR_POUND = '292';
    const CURRENCY_GUATEMALA_QUETZAL = '320';
    const CURRENCY_GUINEA_FRANC = '324';
    const CURRENCY_GUINEABISSAU_PESO = '624';
    const CURRENCY_GUYANESE_DOLLAR = '328';
    const CURRENCY_HAITIAN_GOURDE = '332';
    const CURRENCY_HONDURAS_LIMPERA = '340';
    const CURRENCY_HONG_KONG_DOLLAR = '344';
    const CURRENCY_HUNGARIAN_FORINT = '348';
    const CURRENCY_ICELAND_KRONA = '352';
    const CURRENCY_INDIAN_RUPEE = '356';
    const CURRENCY_INDONESIAN_RUPIAH = '360';
    const CURRENCY_ISRAELI_NEW_SHEKEL = '376';
    const CURRENCY_JAMAICAN_DOLLAR = '388';
    const CURRENCY_JAPANESE_YEN = '392';
    const CURRENCY_KAZAKHSTAN_TENGE = '398';
    const CURRENCY_KENYAN_SHILLING = '404';
    const CURRENCY_KYRGYZSTAN_SOM = '417';
    const CURRENCY_LAOS_KIP = '048';
    const CURRENCY_LATVIAN_LATS = '428';
    const CURRENCY_LEBANESE_POUND = '422';
    const CURRENCY_LITHUANIAN_LITAS = '440';
    const CURRENCY_MACAU_PATACA = '446';
    const CURRENCY_MALAGASY_FRANC = '450';
    const CURRENCY_MALAWI_KWACHA = '454';
    const CURRENCY_MALAYSIAN_RINGGIT = '458';
    const CURRENCY_MALDIVE_RUFIYAA = '462';
    const CURRENCY_MAURITANIA_OUGUIYA = '478';
    const CURRENCY_MAURITIUS_RUPEE = '480';
    const CURRENCY_MEXICAN_PESO = '484';
    const CURRENCY_MOLDOVAN_LEU = '498';
    const CURRENCY_MONGOLIA_TUGRIK = '496';
    const CURRENCY_MOROCCAN_DIRHAM = '504';
    const CURRENCY_MOZAMBIQUE_METICAL = '508';
    const CURRENCY_NAMIBIA_DOLLAR = '516';
    const CURRENCY_NEPALESE_RUPEE = '524';
    const CURRENCY_NETHERLANDS_ANTILLEAN_GUILDER = '532';
    const CURRENCY_NEW_GUINEA_KINA = '598';
    const CURRENCY_NEW_ZEALAND_DOLLAR = '554';
    const CURRENCY_NICARAGUAN_CORDOBA_ORO = '558';
    const CURRENCY_NIGERIAN_NAIRA = '566';
    const CURRENCY_NORWEGIAN_KRONE = '578';
    const CURRENCY_PAKISTAN_RUPEE = '586';
    const CURRENCY_PANAMANIAN_BALBOA = '590';
    const CURRENCY_PARAGUAY_GUARANI = '600';
    const CURRENCY_PERUVIAN_NUEVO_SOL = '604';
    const CURRENCY_PHILIPPINES_PESO = '608';
    const CURRENCY_POLISH_ZLOTY = '985';
    const CURRENCY_QATARI_RIAL = '634';
    const CURRENCY_ROMANIA_LEU = '642';
    const CURRENCY_RUSSIAN_RUBLE = '643';
    const CURRENCY_RWANDA_FRANC = '646';
    const CURRENCY_SAINT_HELENA_POUND = '654';
    const CURRENCY_SAMOAN_TALA = '882';
    const CURRENCY_SAO_TOME_AND_PRINCIPE_DOBRA = '678';
    const CURRENCY_SAUDI_RIYAL = '682';
    const CURRENCY_SEYCHELLES_RUPEE = '690';
    const CURRENCY_SIERRA_LEONEAN_LEONE = '694';
    const CURRENCY_SINGAPORE_DOLLAR = '702';
    const CURRENCY_SOLOMON_ISLANDS_DOLLAR = '090';
    const CURRENCY_SOMALI_SHILLING = '706';
    const CURRENCY_SOUTH_AFRICAN_RAND = '710';
    const CURRENCY_SOUTH_KOREAN_WON = '410';
    const CURRENCY_SRI_LANKA_RUPEE = '144';
    const CURRENCY_SWAZILAND_LILANGENI = '748';
    const CURRENCY_SWEDISH_KRONA = '752';
    const CURRENCY_SWISS_FRANC = '756';
    const CURRENCY_TAIWAN_DOLLAR = '901';
    const CURRENCY_TANZANIAN_SHILLING = '834';
    const CURRENCY_THAI_BAHT = '764';
    const CURRENCY_TONGA_PAANGA = '776';
    const CURRENCY_TRINIDAD_AND_TOBAGO_DOLLAR = '780';
    const CURRENCY_TURKISH_LIRA = '949';
    const CURRENCY_UGANDA_SHILLING = '800';
    const CURRENCY_UKRAINIAN_HRYVNIA = '980';
    const CURRENCY_UNITED_ARAB_EMIRATES_DIRHAM = '784';
    const CURRENCY_URUGUAYAN_PESO = '858';
    const CURRENCY_US_DOLLAR = '840';
    const CURRENCY_UZBEKISTAN_SUM = '860';
    const CURRENCY_VANUATU_VATU = '548';
    const CURRENCY_VENEZUELAN_BOLIVAR = '862';
    const CURRENCY_VIETNAMESE_DONG = '704';
    const CURRENCY_YEMENI_RIAL = '886';
    const CURRENCY_ZAMBIAN_KWACHA = '894';
    const CURRENCY_ZIMBABWE_DOLLAR = '716';

}